feat: COM-3115 Добавил пресет для ссылок соц сетей в футере
CSSSR/core-design pull request #166
Opened 2021-01-27 15:51 UTC by dyurein

## Чек-лист

- [ ] Установил PR в ветку релиза (если есть релизная ветка, в противном случае пункт можно удалить)
- [ ] Убедился что код работает полностью согласно описанию задачи
- [] Проверил работу кода на всех разрешениях
- [ ] Выполнил требования не только из текста задачи, но и из её комментариев
- [ ] Дополнил задачу комментариями для тестирования (при необходимости, в противном случае пункт можно удалить)
- [ ] Убедился что dev-консоль браузера не содержит ошибок
- [ ] Ознакомился с документацией проекта и обновил её при необходимости
- [ ] Добавлены необходимые переменные окружения `ENV` (и документация в `docs/env.md`)

2021-01-28 08:26 UTC, dyurein commented on packages/core-design/src/data/footerPresets.ts
> +    links: socialsEn,
@ArtyomResh Или тут лучше сделать один объект с иконками и выбирать через slice?

2021-02-01 07:49 UTC, ArtyomResh requested changes
А где то что мы обсуждали с тобой про cookiesPolicyLink и privacyPolicyLink? Bottom links? Ты не всё запушил или что-то изменилось в ТЗ?

2021-02-01 07:49 UTC, ArtyomResh commented on packages/core-design/src/data/footerPresets.ts
> +    links: socialsEn,
Хорошая идея 👍

2021-02-01 07:49 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/types.ts
> +  preset?: '' | 'en' | 'ru'
давай назовём пресеты defaultEn и defaultRu

2021-02-01 07:49 UTC, ArtyomResh commented on packages/core-design/src/data/footerPresets.ts
> +    links: socialsEn,
links переименуй в socialLinks, названия ключей в пресеты должны быть такими же как названия пропсов в компоненте, иначе это создаёт путаницу

2021-02-01 07:49 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +          {socialLinks && <SocialLinks links={presets[preset]?.links || socialLinks} />}
Тут не отобразаться социальный линки, если ты передашь только пресет. Можно сделать переменную 
`const socialLinks = presets[preset]?.links || props.socialLinks` и потом сделать так:
`{socialLinks && <SocialLinks links={socialLinks} />}`

2021-02-01 14:16 UTC, dyurein commented
> А где то что мы обсуждали с тобой про cookiesPolicyLink и privacyPolicyLink? Bottom links? Ты не всё запушил или что-то изменилось в ТЗ?

@ArtyomResh Ты про то что переименовал в BottomLinksAndLanguages? Если да, то это обсуждали, что нужно поменять название компонента, т.к в теории могут добавляться другие ссылки в этот компонент

2021-02-03 07:56 UTC, ArtyomResh approved these changes

2021-02-03 08:07 UTC, ArtyomResh commented
Давай только не мержить в мастер в PR 3111 задачи я написал что нужно сделать

2021-02-03 09:56 UTC, merged