feat: COM-3114 Добавил ссылку "frontend.digital" [WIP]
CSSSR/core-design pull request #179
Opened 2021-02-01 12:50 UTC by dyurein

## Чек-лист

- [ ] Установил PR в ветку релиза (если есть релизная ветка, в противном случае пункт можно удалить)
- [x] Убедился что код работает полностью согласно описанию задачи
- [ ] Проверил работу кода на всех разрешениях
- [ ] Выполнил требования не только из текста задачи, но и из её комментариев
- [ ] Дополнил задачу комментариями для тестирования (при необходимости, в противном случае пункт можно удалить)
- [x] Убедился что dev-консоль браузера не содержит ошибок
- [ ] Ознакомился с документацией проекта и обновил её при необходимости
- [ ] Добавлены необходимые переменные окружения `ENV` (и документация в `docs/env.md`)

2021-02-03 07:54 UTC, ArtyomResh requested changes

2021-02-03 07:54 UTC, ArtyomResh commented on packages/core-design/src/data/footerLinks.ts
> +      href: 'http://csssr.com/en',
сделай тут просто `/ru` и `/en`

2021-02-03 07:54 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const allianceLinkPreset = presets[preset].allianceLink
`const allianceLink = props.allianceLink || presets[preset].allianceLink` и так нужно сделать для всех иначе у тебя линк можно будет только через preset передавать и при передаче `allianceLink` ничего не произойдёт

2021-02-03 07:54 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const allianceLinkPreset = presets[preset].allianceLink
Ещё установи `?.` иначе при отсутствии пропса `preset` пресет будет ошибка `couldn't get allianceLink  of undefined`

2021-02-03 07:54 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
>            {isMobile && languageLink && (
Тут для languageLink нужно сделать так же как ты сделал выше для всех остальных на 75-78 строках

2021-02-03 07:54 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  preset: '',
Поставь дефолтный пресет `defaultEn`, данные которые есть в дефолтном пресете можешь удалить выше из defaultProps

2021-02-03 11:23 UTC, dyurein commented on packages/core-design/src/data/footerLinks.ts
> +      href: 'http://csssr.com/en',
Исправил

2021-02-03 11:35 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const allianceLinkPreset = presets[preset].allianceLink
Исправил

2021-02-03 13:14 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const allianceLinkPreset = presets[preset].allianceLink
@ArtyomResh Почему то только для `cookiesPolicyLinkPreset`, если делать `presets[preset]?.cookiesPolicyLink || cookiesPolicyLink`, он передается и рендерится на русской локале, хотя не должен. Не могу понять почему это происходит :/

2021-02-03 13:14 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
>            {isMobile && languageLink && (
Исправил

2021-02-03 13:26 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const allianceLinkPreset = presets[preset].allianceLink
Исправил

2021-02-03 13:27 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
> +  preset: '',
Сделал

2021-02-04 07:48 UTC, ArtyomResh requested changes

2021-02-04 07:48 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const cookiesPolicyLinkPreset = presets[preset]?.cookiesPolicyLink || cookiesPolicyLink
`presets[preset]?` лучше ставить справа, что бы была возможность перезаписывать поверх пресета пропсами ссылок

2021-02-04 07:48 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  nav: defaultNav, // убрать в релизной ветке
Только не убрать, а положить в nav в пресет, а так же addresses, email, actionPhrase и logo href

2021-02-04 07:48 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  nav: defaultNav, // убрать в релизной ветке
Обычно такие комментарии записывают как `TODO: _что нужно сделать_`

2021-02-04 07:48 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  nav: defaultNav, // убрать в релизной ветке
Тут не нужно исправлять

2021-02-04 11:16 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const cookiesPolicyLinkPreset = presets[preset]?.cookiesPolicyLink || cookiesPolicyLink
Понял, исправил

2021-02-04 14:35 UTC, ArtyomResh approved these changes

2021-02-04 16:16 UTC, merged