feat: COM-3111 Добавил ссылку Контакты в футер
CSSSR/core-design pull request #181
Opened 2021-02-02 09:13 UTC by dyurein

## Чек-лист

- [ ] Установил PR в ветку релиза (если есть релизная ветка, в противном случае пункт можно удалить)
- [x] Убедился что код работает полностью согласно описанию задачи
- [x] Проверил работу кода на всех разрешениях
- [ ] Выполнил требования не только из текста задачи, но и из её комментариев
- [ ] Дополнил задачу комментариями для тестирования (при необходимости, в противном случае пункт можно удалить)
- [ ] Убедился что dev-консоль браузера не содержит ошибок
- [ ] Ознакомился с документацией проекта и обновил её при необходимости
- [ ] Добавлены необходимые переменные окружения `ENV` (и документация в `docs/env.md`)

2021-02-03 08:00 UTC, ArtyomResh requested changes
Попроси сделать эпик для всех тасков по футеру на блоге и направь задачи (3111, 3114, 3115) в него. Соберем сначала весь хедер там, а потом уже будем в мастер его мержить

2021-02-03 10:43 UTC, dyurein commented on packages/core-design/src/data/footerLinks.ts
> +        // },
Убрал

2021-02-04 07:41 UTC, ArtyomResh requested changes

2021-02-04 07:41 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +  const navLinks = presets[preset]?.nav || nav
Лучше поменять местами, что бы можно было перезаписывать поверх пресета

2021-02-05 07:47 UTC, merged