feat: COM-3199 Add dataLayer event in footer
CSSSR/core-design pull request #188
Opened 2021-02-16 10:35 UTC by dyurein

## Чек-лист

- [ ] Установил PR в ветку релиза (если есть релизная ветка, в противном случае пункт можно удалить)
- [] Убедился что код работает полностью согласно описанию задачи
- [ ] Проверил работу кода на всех разрешениях
- [ ] Выполнил требования не только из текста задачи, но и из её комментариев
- [ ] Дополнил задачу комментариями для тестирования (при необходимости, в противном случае пункт можно удалить)
- [ ] Убедился что dev-консоль браузера не содержит ошибок
- [ ] Ознакомился с документацией проекта и обновил её при необходимости
- [ ] Добавлены необходимые переменные окружения `ENV` (и документация в `docs/env.md`)

2021-02-16 10:39 UTC, dyurein commented
![image](https://user-images.githubusercontent.com/37905737/108051746-4dd46780-705c-11eb-9253-9f974e221210.png)
Выдает ошибку, запушил с --no-verify

2021-02-17 09:31 UTC, ArtyomResh requested changes

2021-02-17 09:31 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
>      }
Давай повторяющеся вызовы функций вынесем из блока условия и будем их вызывать после этого блока

2021-02-17 09:37 UTC, ArtyomResh commented
> ![image](https://user-images.githubusercontent.com/37905737/108051746-4dd46780-705c-11eb-9253-9f974e221210.png)
> Выдает ошибку, запушил с --no-verify

Заключи этот кусочек кода в комментарии, которые отключают проверку ts

2021-02-19 13:04 UTC, dyurein commented on packages/core-design/src/components/Footer/Footer.tsx
>      }
Вынес

2021-02-19 14:29 UTC, dyurein commented
@ArtyomResh Добавил комменты для tslint, но все равно он не проходит push

2021-02-20 07:10 UTC, ArtyomResh commented
> @ArtyomResh Добавил комменты для tslint, но все равно он не проходит push

Попробуй прописать в файле: 
```
declare global {
    interface Window {
        dataLayer: any;
    }
}
```

или 

```
declare const window: any;
```

2021-02-20 07:10 UTC, ArtyomResh requested changes
Смотри реплай на твой последний коммент

2021-02-20 10:04 UTC, dyurein commented
> > @ArtyomResh Добавил комменты для tslint, но все равно он не проходит push
> 
> Попробуй прописать в файле:
> 
> ```
> declare global {
>     interface Window {
>         dataLayer: any;
>     }
> }
> ```
> 
> или
> 
> ```
> declare const window: any;
> ```

Помогло

2021-02-24 07:39 UTC, ArtyomResh requested changes

2021-02-24 07:39 UTC, ArtyomResh commented on packages/core-design/src/components/Footer/Footer.tsx
> +    /* tslint:disable */
Давай теперь только ненужные комментарии удалим :)

2021-02-25 08:15 UTC, ArtyomResh approved these changes

2021-03-10 11:07 UTC, merged