Релиз storybook через Github Workflow
CSSSR/core-design pull request #189
Opened 2021-02-24 09:58 UTC by verdel

Дополнительно исправил названия svg файлов в footerLinks.ts, так как не проходила сборка storybook

2021-03-02 13:47 UTC, Nitive approved these changes

2021-03-02 13:50 UTC, Nitive requested changes

2021-03-02 13:50 UTC, Nitive commented on .github/kuberta.yaml
> +    chart: csssr/static-site@~1.0.0
Давай возьмём чарт последней версии (и укажем tlsSecret, там это обязательно)

2021-03-02 13:50 UTC, Nitive commented on .github/kuberta.yaml
> +    chart: csssr/static-site@~1.0.0
Сертификат я выписал, поменяв kuberta release для проекта, лежит в секрете `core-design-storybook-tls`

2021-03-02 18:38 UTC, verdel commented on .github/kuberta.yaml
> +    chart: csssr/static-site@~1.0.0
Сделал

2021-03-03 11:30 UTC, Nitive approved these changes

2021-03-04 12:00 UTC, ArtyomResh approved these changes

2021-03-04 12:01 UTC, ArtyomResh commented
Спасибо, парни! :)

2021-03-04 15:23 UTC, ArtyomResh commented
@Nitive @verdel Пинганите меня, пожалуйста, как подмержите

2021-03-04 15:37 UTC, merged